name: DeltaCraftTeams
version: 1.0.0
main: eu.deltacraft.deltacraftteams.DeltaCraftTeams
api-version: 1.17
authors: [ koudy008, Fjarik, Kubas445 ]
website: https://deltacraft.eu
description: DeltaCraft Teams plugin
depend: [ BlueMap ]
commands:
  deltacraftteams:
    description: Main command for DeltaCraftTeams plugins
    usage: /deltacraftteams
    aliases: [ delta, deltacraft ]
  pvp:
    description: Set PVP zones
    usage: /pvp
    aliases: [ pvpzone, pvpzones ]
  sethome:
    description: Set new home
    usage: /sethome
  home:
    description: Teleport home
    usage: /home
  delhome:
    description: Delete home
    usage: /delhome
permissions:
  delta.*:
    default: op
    children:
      delta.home:
        description: Use home command
        default: true
      delta.main.*:
        default: op
        children:
          delta.main.version:
            description: Show curent version
            default: true
          delta.main.show:
            description: Show config
            default: op
          delta.main.reload:
            description: Reload config
            default: op
          delta.main.change:
            description: Change config value
            default: op
      delta.pvp:
        default: op
        children:
          delta.pvp.create:
            description: Create PVP zone
            default: op
          delta.pvp.remove:
            description: Remove PVP zone
            default: op